import { StyleSheet } from "react-native";
import {
  COLORS,
  FONTS,
  FONT_SIZES,
  RADIUS,
  SHADOWS,
  SPACING,
  globalStyles,
} from ".";

export default StyleSheet.create({
  container: {
    ...globalStyles.container,
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.xxxl,
    paddingBottom: SPACING.xl,
    backgroundColor: COLORS.background,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    width: "100%",
  },
  header_left: {
    display: "flex",
    flexDirection: "column",
    alignItems: "baseline",
    gap: 2,
  },
  header_right: {
    display: "flex",
    flexDirection: "column",
    alignItems: "baseline",
  },
  actionsContainer: {
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.md,
    marginBottom: SPACING.lg,
    width: "100%",
    height: "40%",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: SPACING.md,
    fontSize: FONT_SIZES.base,
    color: COLORS.textSecondary,
    fontFamily: FONTS.regular,
  },
  title: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: "600",
    color: COLORS.textPrimary,
    fontFamily: FONTS.semiBold,
  },
  subtitle: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    fontFamily: FONTS.regular,
  },
  permissionContainer: {
    display: "flex",
    backgroundColor: "#b8b8b8ff",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  permissionText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
    fontFamily: FONTS.regular,
  },
  permissionButton: {
    ...globalStyles.buttonPrimary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.xl,
    minHeight: 40,
  },
  permissionButtonText: {
    ...globalStyles.buttonPrimaryText,
    fontSize: FONT_SIZES.sm,
  },
  locationLoading: {
    ...globalStyles.row,
    justifyContent: "center",
    padding: SPACING.base,
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.lg,
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  locationLoadingText: {
    marginLeft: SPACING.md,
    fontSize: FONT_SIZES.sm,
    color: COLORS.textSecondary,
    fontFamily: FONTS.regular,
  },
  mapContainer: {
    width: "100%",
    height: "50%",
    overflow: "hidden",
    ...SHADOWS.medium,
  },
  map: {
    width: "100%",
    height: "100%",
  },
  notificationButton: {
    ...globalStyles.buttonPrimary,
    paddingVertical: 4,
    paddingHorizontal: 16,
    width: "100%",
  },
  logoutButton: {
    ...globalStyles.buttonSecondary,
    paddingVertical: 4,
    paddingHorizontal: 16,
    width: "100%",
  },
  notificationButtonText: {
    ...globalStyles.buttonPrimaryText,
  },
  disabledButton: {
    ...globalStyles.buttonDisabled,
  },
  button: {
    ...globalStyles.buttonSecondary,
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.xs,
    marginBottom: SPACING.xl,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  buttonText: {
    ...globalStyles.buttonSecondaryText,
  },
});
